## gateway-rs configuration file

## Keypair is a string that supports specifying different locations for 
## the secrets. The default one is file based one since all устройства can support it.

# File based: 
keypair = "file:///etc/helium_gateway/gateway_key.bin"

# The address to listen on for the (semtech) packet forwarder
listen = "0.0.0.0:1680"

# The local port to serve the local grpc on. Supports both a simple port number
# or full ip:port listen address. Do NOT expose this port outside of the host
# network for security
api = 4467

[log]
level = "info"
timestamp = true

[poc]
disable = true
entropy_uri = "http://entropy.iot.mainnet.helium.io:7080"
ingest_uri = "http://mainnet-pociot.helium.io:9080"

[config]
pubkey = "137oJzq1qZpSbzHawaysTGGsRCYTXG1MiTMQNxYSsQJp4YMDdN8"
uri = "http://mainnet-config.helium.io:6080/"

[router]
uri = "http://mainnet-router.helium.io:8080/"
queue = 20

## 👇 RADIO CONFIGURATION
[gateway]
model = "RAK2287"

[gateway.commissioning]
gateway_id = ""
key = ""

[gateway.lorawan.radio]
model = "sx1250"
device = "/dev/spidev0.0"
reset_pin = 17
power_en_pin = 18